### ISSUE TITLE
architecture: EAP-TLS with RADIUS

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#10]
Empty section now. Any ideas?

**Comment by vanrein** [comment]
Indeed, not EAP-TTLS; the tunnel for authentication is slower than a client cert, so this is a good showcase for Client DANE.

**Comment by mcr** [comment]
This is indeed a valid use case.  No special concern.
There are two uses: 1) a client-id is passed in the TLS step, 2) a certificate is passed that has a dNSName, at which there is a TLSA RR with ?? in it.

**Comment by vanrein** [comment]
...and the dNSName may 2a) start with a username or 2b) for reasons of username privacy, start with a wildcard name.  The case 2b) has an impact on the authentication, which cannot be simply a strcmp() and on the lookup which needs to wait until the certificate arrives as is also the case for 1).
