### ISSUE TITLE
architecture: Anomaly reporting

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#14]
Missing text. Remove or add?

```
## Operational anomaly reporting

### MUD reporting for improper provisioning

### XARF for abuse reporting

```

**Comment by mcr** [comment]
MUD situation is similiar to #13 , in that the key that signs a MUD file may need to retrieved from DNS.\
How to find the DNS name for verification, and another specification needs to specify this.
Mention this in architecture.   We are looking for XARF expertise.

**Comment by oej** [comment]
Remove text from draft
