### ISSUE TITLE
Architecture: Change of device ownership

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#15]
There was a brief discussion about this on the IETF 115 - can we elaborate?

Current text in the draft:

```
What happens if an organization owning the client identity goes out of business? 
What’s the best way to transfer an identifier to another zone? 
<note: there may be an opportunity here to take advantage of EST, or another protocol supporting certificate renewal, to allow client devices to rotate to another zone>
```

**Comment by oej** [comment]
I personally see one case where DANCE relies on vendor DNS zone and the vendor disappears.

Another is that I’m buying a thing, using the vendors records for bootstrapping then migrating the device into my own safe and comfortable DNS zone. Of course, if the vendor is gone before I get my hands on the thing, the thing is useless.

But is there a need to “transfer”? Isn’t that just me installing a new client cert and/or name in the thing?

**Comment by oej** [comment]
From email @mcr (

Olle E. Johansson <[oej@edvina.net](mailto:oej@edvina.net)> wrote:
We had a very brief discussion of change of ownership in the 115
session, but had to move forward. I would like to open it again on the
list.

```
I think that the major use cases of DANCE is exactly where no change in
ownership (from manufacturer to OwnerOperator) occurs. We said how we didn't
want to force enterprises to run their own (private) PKI, and that's why we
want vendor-anchored DNS names.

If one wants to do a transfer of ownership, then one needs a protocol that
does that. We have DPP, BRSKI(RFC8995), EAP-NOOB, and a few others.

There Security Considerations section of RFC8995 goes into the problem of
what happens when the vendor dies.
```

What happens if an organization owning the client identity goes out of business?
What’s the best way to transfer an identifier to another zone?
<note: there may be an opportunity here to take advantage of EST, or
another protocol supporting certificate renewal, to allow client
devices to rotate to another zone>

`Yes, I'd use EST, and also look at draft-ietf-ACME-integrations.`

I personally see one case where DANCE relies on vendor DNS zone and the vendor disappears.

Another is that I’m buying a thing, using the vendors records for
bootstrapping then migrating the device into my own safe and
comfortable DNS zone. Of course, if the vendor is gone before I get my
hands on the thing, the thing is useless.

```
The thing is probably also useless/dangerous because it gets no further
patches. True ownership transfer involves changing the software update key
too :-)

```
But is there a need to “transfer”? Isn’t that just me installing a new
client cert and/or name in the thing?

`It could be.`

**Comment by oej** [comment]
I think this needs to be in a dedicated IoT document in detail and just mentioned in architecture.

**Comment by mcr** [comment]
The use of DANCE where a client identifier from the manufacturer is used, is precisely the case where 
no change in ownership is desired.  The continued use of the device depends upon the continued existence of the manufacturer.  (This does not preclude third parties from providing some kind of escrow service that replaces the manufacturer.)
