### ISSUE TITLE
Iotdir: Add requirements on "how to dance"

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#52]
1- Section 2, How to Dance with Entity: "... delegates many details of how
DANCE can be used..."  -> It would be nice to add examples of which details,
e.g. "...details such as protocol-specific configurations, security mechanisms,
and interoperability considerations..."

https://datatracker.ietf.org/doc/review-ietf-dance-architecture-06-iotdir-early-robles-2024-07-17/

**Comment by mcr** [comment]
Could there have been an I-D, a template on how to DANCE?
