### ISSUE TITLE
IoTDir: Clarify "security domain" in section 2

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#54]
3- Section 2, Suggestion to complete what it seems to be an open topic: "Is the
security domain defined by how broadly the identity is recognized, or by the
breadth of the application or network access policy?

https://datatracker.ietf.org/doc/review-ietf-dance-architecture-06-iotdir-early-robles-2024-07-17/

**Comment by mcr** [comment]
```
[Is the security domain defined by how broadly the identity is recognized, or by the breadth of the application or network access policy?]
```

**Comment by oej** [comment]
Remove the question.
