### ISSUE TITLE
IotDIR: Complete TBD values

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#55]
4- Section 4.1.1 and 4.1.1.1: Suggestion to complete the TBD values with
further description where to find them.

https://datatracker.ietf.org/doc/review-ietf-dance-architecture-06-iotdir-early-robles-2024-07-17/

**Comment by oej** [comment]
I think we cleared these out after review, but need to validate

**Comment by oej** [comment]
"- If the client's TLSA record matches the presented certificate or public key, the TLS handshake completes successfully and the authenticated dane_clientid is presented to the web application in the (TBD) header field."

Change texts (two places)

**Comment by mcr** [comment]
This would be a DANE equivalent to RFC9440.

**Comment by oej** [comment]
Removed "TBD" - these are detailed in the other draft and isn't needed here.
